### PR TITLE
fixed url for crosswalk

### PR DESCRIPTION
**Pull request by amcgee7**
Signed-off-by: Art McGee <amcgee7@jaguarlandrover.com>

### CODE REVIEW

**Comment by tiagovignatti** [comment]
cool! @nagineni do you want double check this or do you think it's fine to just apply?

**Comment by nagineni** [comment]
Name parameter seems to be not needed since there is only one URI entry, but removing it only from the SRC_URI might break the recipe since we are using that name parameter to specify the checksums.

**Comment by amcgee7** [comment]
My is that it broke my build having the name parameter.  I was unable to
retrieve the source with the name parameter present.  Once I removed the
parameter I was able retrieve the source.  I checked both urls in browsers
as well.  So to me the only other possible change would be to fix the
crosswalk site to allow the name parameter to still retrieve the source.

Thanks,

*Art McGee*
Infotainment Engineer



Jaguar Land Rover North America, LLC
1419 NW 14th Ave, Portland, Oregon, 97209
Jaguar.com <http://jaguar.com>  |  LandRover.com <http://landrover.com>

**Comment by nagineni** [comment]
Hi @amcgee7, 

Build system don't use name parameter as part of url while downloading the sources, so it should not create troubles to download. Also, you should use url without the name parameter in browser to check/download the sources.

https://download.01.org/crosswalk/releases/crosswalk/source/crosswalk_12.40.295.0.tar.xz

The purpose of name parameter is to distinguish between multiple external url entries in SRC_URI and specify the checksums. Like below:

```
SRC_URI += "\
    https://download.01.org/crosswalk/releases/crosswalk/source/crosswalk-${PV}.tar.xz;name=tarball \
    https://${EXAMPLE_SERVER}/releases/source/example-${PV}.tar.xz;name=tarball2 \
    file://use_window_manager_native_decorations.patch \
"

SRC_URI[tarball.md5sum] = "951d93f0089f960d18ceaf9b9aa06e36"
SRC_URI[tarball.sha256sum] = "e744d043ac93f63fef2aa892bcaa6d33a57a9f5ac277a9307eb96cd020296016"
SRC_URI[tarball2.md5sum] = "655efc0d541b03ca5de0ae506c805ea3"
SRC_URI[tarball2.sha256sum] = "2bc071c438e8b0ed42a0bd2db2d8b681b27a1e9b1798694d9874733293bc2aa9"

```

As I mentioned in my previous comment, it's ok to remove the name parameter since there is only one external url entry in crosswalk recipe, but it should also be removed from the SRC_URI checksums. Otherwise, you might get an error saying 'missing SRC_URI checksum', while building the recipe with bitbake.

**Comment by amcgee7** [comment]
Hi, Sudarsana Nagineni

Forgive my ignorance but if it's suppose to be there why does it fail
to during the bitbake giving an error?

Thanks

*Art McGee*
Infotainment Engineer



Jaguar Land Rover North America, LLC
1419 NW 14th Ave, Portland, Oregon, 97209
Jaguar.com <http://jaguar.com>  |  LandRover.com <http://landrover.com>

**Comment by nagineni** [comment]
@amcgee7, could you please paste the error here? I just checked on my machine(with name parameter) and no issues in fetching the sources.

**Comment by nagineni** [comment]
My guess is that your build issue is unrelated to the name parameter.  Anycase, here is the correct patch to remove the name.

```
diff --git a/recipes-crosswalk/crosswalk/crosswalk_12.40.295.0.bb b/recipes-crosswalk/crosswalk/crosswalk_12.40.295.0.bb
index 9e705dc..c90d6f9 100644
--- a/recipes-crosswalk/crosswalk/crosswalk_12.40.295.0.bb
+++ b/recipes-crosswalk/crosswalk/crosswalk_12.40.295.0.bb
@@ -330,14 +330,14 @@ LIC_FILES_CHKSUM = "\
     "
 
 SRC_URI += "\
-    https://download.01.org/crosswalk/releases/crosswalk/source/crosswalk-${PV}.tar.xz;name=tarball \
+    https://download.01.org/crosswalk/releases/crosswalk/source/crosswalk-${PV}.tar.xz \
     file://use_window_manager_native_decorations.patch \
     file://pick_yocto_compiler.patch \
     file://include.gypi \
     "
 
-SRC_URI[tarball.md5sum] = "951d93f0089f960d18ceaf9b9aa06e36"
-SRC_URI[tarball.sha256sum] = "e744d043ac93f63fef2aa892bcaa6d33a57a9f5ac277a9307eb96cd020296016"
+SRC_URI[md5sum] = "951d93f0089f960d18ceaf9b9aa06e36"
+SRC_URI[sha256sum] = "e744d043ac93f63fef2aa892bcaa6d33a57a9f5ac277a9307eb96cd020296016"
 
 COMPATIBLE_MACHINE = "(-)"
 COMPATIBLE_MACHINE_i586 = "(.*)"
```

**Comment by kteza1** [comment]
Hi. Is this going to be updated to latest version of crosswalk? Or is this project scrapped on yocto?

**Comment by rakuco** [comment]
We intend to pick up the work on Crosswalk on Yocto and start maintaining it again. I may not happen immediately, but it is definitely something we want to start doing as soon as possible.

**Comment by kteza1** [comment]
Thanks. Hope this happens soon :+1:

**Pull request closed without merging**
